# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_made_by', models.CharField(db_index=True, max_length=15)),
                ('request_sent_to', models.CharField(db_index=True, max_length=15)),
                ('sender_full_name', models.CharField(max_length=256)),
                ('receiver_full_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
